/**
 * Generate a typed token surface from tokens.json.
 *
 * Output (to src/):
 *   tokens.ts — the token name union, the runtime constant map, per-token
 *               metadata, and typed helper accessors. Every helper takes a
 *               `TokenName`, so a misspelled token is a compile error.
 *
 * Deliberately ONE file: emitting tokens.d.ts alongside tokens.ts would make
 * TypeScript prefer the .d.ts and ignore the real implementation.
 *
 * Scope note: this CANNOT narrow `CSSStyleDeclaration.setProperty` by interface
 * merging — lib.dom.d.ts types it as `property: string`, and a re-declaration
 * only adds an overload rather than replacing it. Hence `setToken()`.
 *
 * Why this exists: the official token names ship inside the theme bundle but have
 * no typed surface, so a misspelled `--dsw-*` silently produces no style. This
 * file is regenerated per DSH release to restore autocomplete and typo detection.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const data = JSON.parse(readFileSync(new URL('tokens.json', root), 'utf8'));
const tokens = data.tokens;

/** How often the shell's own shipped artifacts reference each token. */
const usage = new Map(
  JSON.parse(readFileSync(new URL('usage.json', root), 'utf8')).used,
);

/**
 * A stable label for the source bundle. `data.source` is an absolute local path
 * that differs per machine, so never bake it into committed output.
 */
const SOURCE_LABEL = '@deepseek-ai/dsh-client-ui-theme/lib/client.js';

/** Split into the groups the generated surface actually distinguishes. */
const themeVarying = tokens.filter((t) => t.theme === 'light+dark');
const themeInvariant = tokens.filter((t) => t.theme !== 'light+dark');
const palette = tokens.filter((t) => t.purpose === 'palette');
const semantic = tokens.filter((t) => t.purpose !== 'palette');

const header = `/**
 * AUTO-GENERATED by tools/gen-types.mjs — do not edit by hand.
 *
 * Source: ${SOURCE_LABEL}
 * Generated from ${data.counts.total} design tokens extracted from the DSH web shell.
 * Re-run \`node tools/extract-tokens.mjs && node tools/gen-types.mjs\` after a DSH upgrade.
 */`;

// ---------------------------------------------------------------- tokens.ts

const ts = [];
ts.push(header);
ts.push('');
ts.push('/** Every design token the DSH web shell ships, as a name → custom-property map. */');
ts.push('export const tokens = {');
for (const t of tokens) {
  ts.push(`  ${JSON.stringify(t.token)}: ${JSON.stringify(`var(${t.token})`)},`);
}
ts.push('} as const;');
ts.push('');
ts.push('/** A design token name, e.g. `--dsw-alias-label-primary`. */');
ts.push("export type TokenName = keyof typeof tokens;");
ts.push('');
ts.push('/** Token names whose value flips between light and dark theme. */');
ts.push('export const themeVaryingTokens = [');
for (const t of themeVarying) ts.push(`  ${JSON.stringify(t.token)},`);
ts.push('] as const satisfies readonly TokenName[];');
ts.push('');
ts.push('/** Token names that are identical in both themes. */');
ts.push('export const themeInvariantTokens = [');
for (const t of themeInvariant) ts.push(`  ${JSON.stringify(t.token)},`);
ts.push('] as const satisfies readonly TokenName[];');
ts.push('');
ts.push('/** Raw palette entries. Prefer the `--dsw-alias-*` semantic layer instead. */');
ts.push('export const paletteTokens = [');
for (const t of palette) ts.push(`  ${JSON.stringify(t.token)},`);
ts.push('] as const satisfies readonly TokenName[];');
ts.push('');
ts.push('/** Semantic (non-palette) tokens — the ones application code should use. */');
ts.push('export const semanticTokens = [');
for (const t of semantic) ts.push(`  ${JSON.stringify(t.token)},`);
ts.push('] as const satisfies readonly TokenName[];');
ts.push('');
ts.push('/**');
ts.push(' * The per-token metadata the shell exposes to us: which layer it belongs to,');
ts.push(' * what it is for, whether it flips with the theme, and how often the shell uses it.');
ts.push(' */');
ts.push('export interface TokenMeta {');
ts.push('  readonly layer: string;');
ts.push('  readonly purpose: string;');
ts.push("  readonly theme: 'light+dark' | 'invariant' | string;");
ts.push('  readonly scopes: readonly string[];');
ts.push('  readonly usageCount: number;');
ts.push('}');
ts.push('');
ts.push('/** Metadata for every token, keyed by token name. */');
ts.push('export const tokenMeta: Readonly<Record<TokenName, TokenMeta>> = {');
for (const t of tokens) {
  const u = usage.get(t.token) ?? 0;
  ts.push(
    `  ${JSON.stringify(t.token)}: { layer: ${JSON.stringify(t.layer)}, ` +
    `purpose: ${JSON.stringify(t.purpose)}, theme: ${JSON.stringify(t.theme)}, ` +
    `scopes: ${JSON.stringify(t.scopes)}, usageCount: ${u} },`
  );
}
ts.push('};');
ts.push('');
ts.push('/**');
ts.push(' * Read one token as a CSS `var(...)` expression.');
ts.push(' * @param name - a known token name; a typo is a compile error.');
ts.push(' * @param fallback - optional fallback value, appended after a comma.');
ts.push(' */');
ts.push('export function token(name: TokenName, fallback?: string): string {');
ts.push('  return fallback === undefined ? tokens[name] : `var(${name}, ${fallback})`;');
ts.push('}');
ts.push('');
ts.push('/**');
ts.push(' * Build a React inline-style object from token values.');
ts.push(' * @param decls - CSS property → token name; typos are compile errors.');
ts.push(' */');
ts.push('export function tokenStyle(');
ts.push('  decls: Record<string, TokenName>,');
ts.push('): Record<string, string> {');
ts.push('  const out: Record<string, string> = {};');
ts.push('  for (const [prop, name] of Object.entries(decls)) out[prop] = token(name);');
ts.push('  return out;');
ts.push('}');
ts.push('');
ts.push('/**');
ts.push(' * Append a token as a class name, for use with a CSS Module lookup.');
ts.push(' * @param name - a known token name.');
ts.push(' */');
ts.push('export function tokenClass(name: TokenName): string {');
ts.push('  return `dsh-token-${name.slice(2)}`;');
ts.push('}');
ts.push('');
ts.push('/**');
ts.push(' * Set one design token on an element.');
ts.push(' *');
ts.push(' * This wrapper exists because `CSSStyleDeclaration.setProperty` CANNOT be');
ts.push(' * narrowed by declaration merging: lib.dom.d.ts declares it as');
ts.push(' * `setProperty(property: string, value: string | null, priority?: string)`');
ts.push(' * and an interface re-declaration only ADDS an overload — the broad `string`');
ts.push(' * signature keeps accepting any name. Routing through this function is what');
ts.push(' * actually makes a misspelled token a compile error.');
ts.push(' *');
ts.push(' * @param el - the element to style.');
ts.push(' * @param name - a known token name; a typo is a compile error.');
ts.push(' * @param value - the CSS value to assign.');
ts.push(' */');
ts.push('export function setToken(el: { style: CSSStyleDeclaration }, name: TokenName, value: string): void {');
ts.push('  el.style.setProperty(name, value);');
ts.push('}');
ts.push('');

mkdirSync(new URL('src', root), { recursive: true });
writeFileSync(new URL('src/tokens.ts', root), ts.join('\n'));
console.log(`src/tokens.ts   ${ts.length} lines`);
console.log(`tokens: ${tokens.length} (semantic ${semantic.length}, palette ${palette.length}, theme-varying ${themeVarying.length})`);
